name: redstone_mapper
version: 0.2.0-beta.1+1
author: Luiz Mineo <luiz.mineo@gmail.com>
description: A mapper plugin for Redstone.dart
homepage: http://redstonedart.org
environment:
  sdk: '>=1.9.0-dev.9.1 <2.0.0'
dependencies:
  redstone:
    git: https://github.com/vgordievskiy/redstone.git
  analyzer: any
  code_transformers: any
dev_dependencies:
  unittest: any
transformers:
  - redstone_mapper
